language: python
python:
  - 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gpsd gpsd-clients python-gps
install:
  - pip install coveralls
script:
  - nosetests  --with-coverage --cover-package=src
after_success:
  - coveralls