language: python
sudo: true
branches:
  only:
    - master
python:
  - '2.7_with_system_site_packages'
before_install:
  - pip install -U pip
  - sudo apt-get install -qq gpsd gpsd-clients python-gps
install:
  - travis_wait travis_retry pip install coveralls
script:
  - nosetests  --with-coverage --cover-package=src